[build]
  publish = "."

[build.environment]
  # Disable Netlify's image optimization
  NETLIFY_IMAGE_CDN = "false"

[[plugins]]
  package = "@netlify/plugin-image-cdn"
  [plugins.inputs]
    disable = true